plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.magic76.crew'
version = '0.1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    withSourcesJar()
}

publishing {
    publications {
        agentCore(MavenPublication) {
            from components.java
            artifactId = 'agent-core'
        }
    }
}
