plugins {
    id 'com.android.application'
}

android {
    namespace 'com.crewpocket.helper'
    compileSdk 34

    defaultConfig {
        applicationId "com.crewpocket.helper"
        minSdk 24
        targetSdk 34
        versionCode 100
        versionName "1.8.63"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'], exclude: ['sherpa-onnx-*.jar', 'kotlin-*.jar', 'annotations-*.jar'])
    implementation files('libs/sherpa-onnx-1.13.7.aar')
    implementation files('libs/kotlin-stdlib-1.7.20.jar')
    implementation files('libs/kotlin-stdlib-common-1.7.20.jar')
    implementation files('libs/kotlin-stdlib-jdk7-1.7.20.jar')
    implementation files('libs/kotlin-stdlib-jdk8-1.7.20.jar')
    implementation files('libs/annotations-13.0.jar')
}
